config/routes.rb
Controlador::Application.routes.draw do
  get "static_pages/home"
  devise_for :users, :controllers => { :registrations => "registrations" }  
  
  resources :projects do
    resources :tickets
  end

  resources :projects, :only => :index

  root :to => 'static_pages#home'

  

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :tickets

	after_create :new_project_notification
	after_save :project_change_notification, :if => :name_changed?

	validates_presence_of :name,:user
	validates_length_of :name, maximum: 255
	validates_uniqueness_of :name 

	def next_friendly_id_ticket
		return tickets.count + 1
	end

	def progress
		@percentage ||= calculate_progress_percentage
	end

	def filter_tickets query
		if query == "Completed"
			tickets.where(completed: true)
		elsif query == "NotCompleted"
			tickets.where(completed: false)
		else
			tickets
		end
	end

	private

	def calculate_progress_percentage
		#refactor this method! We really need to set tickets_completed and tickets_all? How about scope?
		tickets_completed = tickets.where(completed: true).count()
		tickets_all = tickets.count
		tickets_all != 0 ? (tickets_completed.fdiv(tickets_all)) * 100 : 0
	end

	def new_project_notification
		ProjectMailer.new_project(self).deliver
	end

	def project_change_notification
		#ProjectMailer.project_change(self).deliver
	end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :project

	before_create :set_friendly_id

	#validates :friendly_id, presence: true
	validates :description, presence: true
	validates :project, presence: true
	validates :description, length: { maximum: 255 }

	def set_friendly_id
		self.friendly_id ||= project.next_friendly_id_ticket
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, -> { order(start: :desc) }

  validates :name, :email, presence: true
  validates :name, length: { minimum: 4, maximum: 60 }

  def is_admin?
    self.try(:admin?)
  end

  def list_valid_projects
    is_admin? ? Project.all : projects
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :store_location

	def store_location
	  # store last url - this is needed for post-login redirect to whatever the user last visited.
	  if (request.fullpath != "/users/sign_in" &&
	      request.fullpath != "/users/sign_up" &&
	      request.fullpath != "/users/password" &&
	      !request.xhr?) # don't store ajax calls
	    session[:previous_url] = request.fullpath 
	  end
	end

	def after_sign_in_path_for(resource)
	  session[:previous_url] || root_path
	end

	def is_admin?
   	current_user.is_admin?
  end

	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @tickets = @project.filter_tickets(params[:query])
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
    redirect_to project_path @project unless is_admin? || current_user == @project.user
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_path(@project), notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update    
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_path(@project), notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :start, :prevision)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

	protected
	  def after_sign_up_path_for(resource)
	    root_path
	  end

  private
 
	  def sign_up_params
	    params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end
 
  	def account_update_params
	    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
	  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy, :new, :create]
  before_action :authenticate_user!

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new    
  end

  # GET /tickets/1/edit
  def edit
    
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = @project.tickets.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to project_ticket_path(@project, @ticket) , notice: 'Ticket was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ticket }
      else
        format.html { render action: 'new' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to project_ticket_path(@project, @ticket), notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:friendly_id, :description, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def wrap(content)
			sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
		end

			private
				def wrap_long_string(text, max_width = 30)
					zero_width_space = "&#8203;"
					regex = /.{1,#{max_width}}/
				       (text.length < max_width) ? text : text.scan(regex).join(zero_width_space)
				end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/_header.html.erb
<header>
  <%= render 'layouts/navigation' %>
</header>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Twitter Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Controlador</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>

  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
	<li><%= link_to	"Projetos", projects_path %></li>
	<li><%= link_to	current_user.email, edit_user_registration_path %></li>
	<li><%= link_to	"Log out", destroy_user_session_path, :method => :delete %></li>
<% else %>
	<li><%= link_to	"Sign Up", new_user_registration_path %></li>
	<li><%= link_to	"Log in", new_user_session_path %></li>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Controlador" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Controlador" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/messages' %>
    <%= yield %>      
    <hr/>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for [@project] do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start %><br>
    <%= f.date_select :start %>
  </div>
  <div class="field">
    <%= f.label :prevision %><br>
    <%= f.date_select :prevision %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project_board.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">
            Project Options
        </h3>
    </div>
    <div class="panel-body">
        <%= link_to 'CREATE TICKET', new_project_ticket_path(@project),
                                { :class => 'btn btn-danger btn-sm btn-block', :role => 'button' } %>
        <hr />
        <ul class="nav nav-pills nav-stacked">
            <li class="active">
                <%= link_to project_path(@project) do %>
                    <span class="badge pull-right"><%= @project.tickets.count %></span> All 
                <% end %>
            </li>
            <li>
                <%= link_to 'Not Complete', project_path(@project, query: "NotCompleted") %>
            </li>
            <li>
                <%= link_to 'Complete', project_path(@project, query: "Completed") %>
            </li>
            <li><a href="http://www.jquery2dotnet.com">Important</a></li>
            <li><a href="http://www.jquery2dotnet.com">Sent Mail</a></li>
            <li><a href="http://www.jquery2dotnet.com"><span class="badge pull-right">3</span>Drafts</a></li>
        </ul>
    </div>
    <div class="panel-footer">
        Panel footer
    </div>
</div>

app/views/projects/_project_item.html.erb
<div class="row well" id="<%= project_item.id %>">
    <div class="col-md-3">
        <img alt="150x150" src="http://lorempixel.com/150/150/" />
    </div>
    <div class="col-md-9">
        <h4>
            <strong><%= project_item.name %></strong>
        </h4>
        <div class="progress progress-striped active">
            <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0"
                     aria-valuemax="<%= project_item.progress %>" style="width: <%= project_item.progress %>%;">
                     <%= number_to_percentage(project_item.progress, precision: 2) %>
          </div>
        </div>
        <div class="btn-group btn-group-xs">
            <%= link_to new_project_ticket_path(project_item), :class => "btn btn-default" do %>
                <em class="glyphicon glyphicon-record"></em> Add Ticket
            <% end %>
            <%= link_to edit_project_path(project_item), :class => "btn btn-default" do %>
                <em class="glyphicon glyphicon-edit"></em> Edit Project
            <% end %>
            <%= link_to project_path(project_item), 
                                    method: :delete, data: { confirm: 'Are you sure?' } , 
                                    :class => "btn btn-default" do %>
                <em class="glyphicon glyphicon-remove"></em> Remove Project
            <% end %>
            <a href="" class="btn btn-default">
                <em class="glyphicon glyphicon-question-sign"></em> Ask Question
            </a>
        </div>
        <div class="pull-right">
            <%= link_to 'GO!', project_path(project_item.id), :class => "btn btn-primary" %>
        </div>
    </div>
</div>



<!--
<li id="<%= project_item.id %>">
  <%= link_to project_path(project_item), :class => "list-group-item" do %>
    <div class="checkbox">
        <label>
            <input type="checkbox" />
        </label>
    </div>
    <span class="glyphicon glyphicon-star-empty projectDone"></span>
    <span class="name" style="min-width: 120px; display: inline-block;">
    	<h4><%= project_item.name %></h4>      
    </span> 
    <span class="">
      <%= wrap(project_item.description) %>
    </span>
    <span class="badge">Criado <%= time_ago_in_words(project_item.created_at) %> ago.</span>
  <% end %>
</li>
-->

app/views/projects/edit.html.erb
<div class="container">
	<h1>Editing project</h1>

	<%= render 'form' %>

	<%= link_to 'Show', [@project] %> |
	<%= link_to 'Back', projects_path %>	
</div>

app/views/projects/index.html.erb
<div class="container">
  <h1>Projetos</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Data Início</th>
        <th>Previsão</th>
        <% if current_user.is_admin? %>
          <th>Dono</th>
        <% end %>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.description %></td>
          <td><%= project.start %></td>
          <td><%= project.prevision %></td>

          <% if current_user.is_admin? %>
            <td><%= project.get_owner %></td>
          <% end %>
          <td><%= link_to 'Show', project_path(project) %></td>
          <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_project_path(project) %></td>
            <td><%= link_to 'Destroy', project_path(project), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>        
        </tr>
      <% end %>
    </tbody>
  </table>

</div> 

app/views/projects/new.html.erb
<div class="container">
	<h1>New project</h1>

	<%= render 'form' %>

	<%= link_to 'Back', root_url %>
</div>

app/views/projects/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    	<span class="glyphicon glyphicon-briefcase"></span>
    	<span class="text-muted"><%= @project.name %></span>
  	</h3>
  </div>
  <div class="panel-body">
    <div class="row">
			<div class="col-md-2">
		    <%= render partial: 'project_board' %>
			</div>
			<div class="list-group col-md-10">
				<ul class="model_list">
					<%= render partial: 'tickets/ticket_item', collection: @tickets %>
				</ul>
			</div>
		</div>
  </div>
</div>

app/views/shared/_home_logged.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">
    	<span class="glyphicon glyphicon-briefcase"></span>
    	<span class="text-muted">Painel de controle</span>
  	</h3>
  </div>
  <div class="panel-body">
    <div class="row">
			<div class="col-md-3">
		    <%= render partial: 'shared/user_board' %>
			</div>
			<div class="col-md-9">
				<%= render partial: 'projects/project_item', collection: current_user.projects %>
			</div>
		</div>
  </div>
</div>

app/views/shared/_user_board.html.erb
<div class="options">
    <%= link_to 'CREATE PROJECT', new_project_path,
                                { :class => 'btn btn-danger btn-sm btn-block', :role => 'button' } %>
    <hr />
    <ul class="nav nav-pills nav-stacked">
        <li class="active"><a href="#"><span class="badge pull-right">42</span> Inbox </a>
        </li>
        <li><a href="http://www.jquery2dotnet.com">Starred</a></li>
        <li><a href="http://www.jquery2dotnet.com">Important</a></li>
        <li><a href="http://www.jquery2dotnet.com">Sent Mail</a></li>
        <li><a href="http://www.jquery2dotnet.com"><span class="badge pull-right">3</span>Drafts</a></li>
    </ul>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<% if user_signed_in? %>
  <%= render 'shared/home_logged' %>
<% else %> 
  <%= render 'shared/home_not_logged' %>
<% end %> 

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :completed %><br>
    <%= f.check_box :completed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/_ticket_item.html.erb
<li id="<%= ticket_item.id %>">
  <%= link_to project_ticket_path(@project, ticket_item), :class => "list-group-item" do %>
    <div class="checkbox">
        <label>
            <input type="checkbox" />
        </label>
    </div>
    <span class="glyphicon glyphicon-star-empty"></span>
    <span class="name" style="min-width: 120px; display: inline-block;">
    	<h4>#<%= ticket_item.friendly_id %></h4>
    </span>
    <span class="">
      <%= wrap(ticket_item.description) %>
    </span>
    <span class="badge">Criado <%= time_ago_in_words(ticket_item.created_at) %> ago.</span>
  <% end %>
</li>


<script type="text/javascript">
    $(document).ready(function(){
        $('.projectDone').on('click', function(event){
            event.preventDefault();
            var el = $('.projectDone').closest('li');
            execute(el);
        });
        

        var execute = function(el){
            var element = el;
            $.ajax({
                url: "projects/complete",
                type: "POST",
                data: {id: element.val()},
                success: function (data) {
                  alert(data);
                }
            });
        };
    });    
</script>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', project_ticket_path(@project, @ticket)  %> |
<%= link_to 'Back', project_path(@project) %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tickets_path(@project) %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row clearfix">
	<div class="col-md-12 column">
		<h3>
			Project: <%= @ticket.project.name %> Ticket number <strong><%= @ticket.friendly_id %></strong>
		</h3>
		<p>
			<%= @ticket.description %>
		</p>
		<p>
			<%= @ticket.completed %>
		</p>

		<%= link_to 'Edit', edit_project_ticket_path(@project, @ticket) %> |
		<%= link_to 'Back', project_path(@project) %>
	</div>
</div>